"""add completed to shopping list item

Revision ID: 285dcace1372
Revises: 85361c0794de
Create Date: 2026-09-13 15:08:56.057868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285dcace1372'
down_revision: Union[str, Sequence[str], None] = '85361c0794de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_items', 'completed')
    # ### end Alembic commands ###
