"""add taget stock to items

Revision ID: 45aaa1266cfd
Revises: 52e574cf75db
Create Date: 2026-08-29 17:23:41.708114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45aaa1266cfd'
down_revision: Union[str, Sequence[str], None] = '52e574cf75db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('target_stock', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'target_stock')
    # ### end Alembic commands ###
