"""add stocked to shopping list item

Revision ID: 85361c0794de
Revises: 45aaa1266cfd
Create Date: 2026-09-06 13:41:44.487993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85361c0794de'
down_revision: Union[str, Sequence[str], None] = '45aaa1266cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column('stocked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('shopping_list_items', 'stocked', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_items', 'stocked')
    # ### end Alembic commands ###
